### ISSUE TITLE
Component always hydrates after render of the withHydrationOnDemand component

### ISSUE THREAD

**Issue by kije** [valcol/react-hydration-on-demand#13]
I'm having an issue with this library, but I'm not quite sure if I'm missing something.

I have roughly the following setup (simplified):
```jsx
// App.jsx
import React, { useState, useEffect } from "react";
import withHydrationOnDemand from "react-hydration-on-demand";
import { Footer } from "./footer";

// also tried with options like { on: ["visible"]} etc...
// note: this should never hydrate on the client, and only be rendered once statically during SSR -> So displayed text in Footer should always be "Is not mounted (hydration pending)"
const LazyFooter = withHydrationOnDemand()(Footer);

const App = () => {
  console.log('Render App');
  const [someState, setSomeState] = useState(0);
  
  // some logic that causes the component to render/execute multiple times
  useEffect(() => {
    const interval = setInterval(() => {
      setSomeState((s) => s + 1);
    }, 1000);
    
    return () => clearInterval(interval);
  }, [])
  
  return (
    <div>
      <div style={{ height: "200vh" }}>
        Some content {someState}
      </div>
      <LazyFooter />
    </div>
  );
};

```

```jsx
// footer.jsx
import React, { useState, useEffect } from "react";

const Footer = () => {
  // this should only execute on the client side, once this component has been hydrated
  console.log('Render Footer');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, [])


  return (
    <div className="footer">
      {isMounted ? "Is Mounted" : "Is not mounted (hydration pending)"}
    </div>
  );
};

export {Footer};
```

When I now build my app using SSR, the outputted HTML contains the fully rendered component as expected, also with the `data-hydration-on-demand="true"` attribute:

```html
<div>
  <div style="height: 200vh">
    Some content 0
  </div>
  <section data-hydration-on-demand="true">
    <div class="footer">
      Is not mounted (hydration pending)
    </div>
  </section>
</div>

```
However, if I then open the app in my browser, the footer component gets hydrated immediately after mounting of the app. I can confirm this by the console output (see console.log above) as well as looking at the rendered text in the footer. The HTML of my App after mount then looks something like this:

```html
<div>
  <div style="height: 200vh">
    Some content 2
  </div>
  <section>
    <div class="footer">
      Is Mounted
    </div>
  </section>
</div>

```

Investigating this a bit, I observed tho following happening, leading to this bug:

1. App mounts
2. LazyFooter renders
3. inside WithHydrationOnDemand, [`isHydrated` state is initially set to false](https://github.com/valcol/react-hydration-on-demand/blob/master/src/index.js#L37)
4. Thus, the ["Placeholder" compnent](https://github.com/valcol/react-hydration-on-demand/blob/master/src/index.js#L145) gets rendered. Note: this removes the `data-hydration-on-demand="true"` attribute from the placeholder
5. `useLayoutEffect` gets executed
6. [wasRenderedServerSide](https://github.com/valcol/react-hydration-on-demand/blob/master/src/index.js#L127) is set to false, since the `data-hydration-on-demand="true"` attribute is not present anymore
7. [`hydrate()`](https://github.com/valcol/react-hydration-on-demand/blob/master/src/index.js#L132) gets called
8. this causes the `Footer` component to mount on the next render, since `hydrate()` sets `isHydrated` to true

So, the issue seems to be that `data-hydration-on-demand="true"` gets removed on the first render.

**Comment by valcol** [comment]
The issue is at the step 4, the data attribute should still be there. 

I made a quick codesandbox with your code, and I could not reproduce the problem you're describing: https://codesandbox.io/s/react-hydration-on-demand-issue-13-cj6oy
