### ISSUE TITLE
Hydrates to empty html with code splitting

### ISSUE THREAD

**Issue by Pranab16** [valcol/react-hydration-on-demand#18]
I'm having an issue with this library, but I'm not quite sure if I'm missing something.

If the parent component is a chunk using code-splitting(@loadable/component), then it hydrates to empty html which ultimately leads to rendering of component on client side.

I forked your codesandbox to reproduce the issue:
https://codesandbox.io/s/react-hydration-on-demand-issue-13-forked-47xrw

**Comment by valcol** [comment]
I'm not sure what your specific use case is, but if you want to use `@loadable/component` I recommend that you let `react-hydration-on-demand` handle the chunk preloading and the render : 

```js
import withHydrationOnDemand from "react-hydration-on-demand";
import loadable from "@loadable/component";

const LoadableCard = loadable(() => import("../Card"));
const CardWithHydrationOnDemand = withHydrationOnDemand({
    on: ["visible"],
    onBefore: LoadableCard.load,
})(LoadableCard);
```

This will keep the content rendered server-side until the chunk is fully loaded. 
https://codesandbox.io/s/react-hydration-on-demand-issue-18-4kleu
