### ISSUE TITLE
Display inline-block

### ISSUE THREAD

**Issue by Burdigalais** [valcol/react-hydration-on-demand#2]
Hello, 

Why you add style `display: inline-block` on section ? 
You should use a `display: inherit` to avoid breaking the existing style (: 

![image](https://user-images.githubusercontent.com/51970896/72329753-9b421080-36b5-11ea-8ac7-29ec842fa83f.png)

_Thank._

**Comment by valcol** [comment]
Hello, 

This should no longer be a problem with the latest release, as there is no more style on the wrapper. 
If needed you can also pass a custom style prop via the `wrapperProps`.
