### ISSUE TITLE
[Question] keyboard focus

### ISSUE THREAD

**Issue by Sin1tar** [valcol/react-hydration-on-demand#21]
Hello, thank you for this great library!

If i add "focus" event to the component, then after hydration focus will reset.
Is it possible to focus on element after hydration?

Thanks!

**Comment by valcol** [comment]
Hello, yes it's possible.

For example here is how it can be done on a input: https://codesandbox.io/s/react-hydration-on-demand-issue-21-xjln9m
In this example the input will keep its content and focus.

Let me know if this doesn't answer your question.

**Comment by Sin1tar** [comment]
> Hello, yes it's possible.
> 
> For example here is how it can be done on a input: https://codesandbox.io/s/react-hydration-on-demand-issue-21-xjln9m In this example the input will keep its content and focus.
> 
> Let me know if this doesn't answer your question.

Thank you! All works nice)
