### ISSUE TITLE
Renders empty html on client side until hydration is done 

### ISSUE THREAD

**Issue by Pranab16** [valcol/react-hydration-on-demand#4]
Won't this code render empty html?

```
<section
          ref={rootRef}
          dangerouslySetInnerHTML={{ __html: "" }}
          suppressHydrationWarning
          {...wrapperProps}
        />
```

**Comment by kije** [comment]
For reference:
https://github.com/facebook/react/issues/8017#issuecomment-413871768

-> no, seems like `dangerouslySetInnerHTML={{ __html: "" }}` is the way to tell react to keep the content of that DOM-Node (alltough not the node itself -> related issue https://github.com/valcol/react-hydration-on-demand/issues/13) as it is

**Comment by valcol** [comment]
No, this will keep the DOM rendered server-side when used with `ReactDOM.hydrate`.

**Comment by lamysafari** [comment]
> No, this will keep the DOM rendered server-side when used with `ReactDOM.hydrate`.

Could you explain why React does not use empty strings and discard SSR-rendered content? How did you discover this method?
